export const GET_BANNER_CONTENT_REQUEST = "GET_BANNER_CONTENT_REQUEST"

export const GET_BANNER_CONTENT_SUCCESS = "GET_BANNER_CONTENT_SUCCESS"

export const GET_BANNER_CONTENT_FAILS = "GET_BANNER_CONTENT_FAILS"
